version: '3.8'
services:
  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    image: docker.vectorized.io/vectorized/redpanda:v23.3.15
    container_name: redpanda-1
    ports:
      - 9092:9092
      - 29092:29092

  kafdrop:
    image: obsidiandynamics/kafdrop
    environment:
      KAFKA_BROKERCONNECT: "redpanda:29092"
      JVM_OPTS: "-Xms32M -Xmx64M"
    ports:
      - 9000:9000
    depends_on:
      - redpanda
